create api evaluation 123
theitm/my-room-mate pull request #5
Opened 2022-03-30 09:42 UTC by NguyenVanHai1705

done api evaluation

2022-03-30 09:55 UTC, thcong98 commented on pom.xml
> -        </dependency>
phần này nên bỏ vì  mình dùng mysql

2022-03-30 11:27 UTC, VanTay404 commented on src/main/java/motelRoom/entity/EvaluationEntity.java
> +    @Column(name = "time_rate")
Nên đổi String sang Date

2022-03-30 11:27 UTC, VanTay404 commented on src/main/java/motelRoom/service/EvaluationService/EvaluationServiceImpl.java
> +    public void  SaveUpdate(UUID id,    EvaluationCreateDto createDto){
Nên sửa lại khoảng cách

2022-03-30 12:13 UTC, thcong98 commented on src/main/java/motelRoom/service/EvaluationService/EvaluationServiceImpl.java
> +    public void  SaveUpdate(UUID id,    EvaluationCreateDto createDto){
hàm này chưa được sử dụng

2022-03-30 12:17 UTC, thcong98 commented on src/main/java/motelRoom/service/EvaluationService/EvaluationServiceImpl.java
> +    public EvaluationDetailDto updateEvaluation(UUID id, EvaluationCreateDto evaluationCreateDto) {
hàm này nên bỏ!

2022-03-30 12:19 UTC, thcong98 commented on src/main/java/motelRoom/service/EvaluationService/EvaluationServiceImpl.java
> +    public void  SaveUpdate(UUID id,    EvaluationCreateDto createDto){
chú ý đặt tên hàm! SaveUpdate -> saveUpdate

2022-03-31 02:51 UTC, daoduytuong requested changes
![image](https://user-images.githubusercontent.com/76141709/160966230-1f0aead5-21e5-4ed5-8981-a4e7601464df.png)
Hải kiểm tra lại folder DTO tồn tại 2 folder "Evaluation" và "valuation"

2022-03-31 02:51 UTC, daoduytuong commented on src/main/java/motelRoom/dto/valuation/EvaluationCreateDto.java
>      private String rate;
"rate" >> type Float

2022-03-31 03:21 UTC, daoduytuong commented on src/main/java/motelRoom/dto/valuation/EvaluationCreateDto.java
> +    private UUID evaluation_id;
bỏ  "private UUID evaluation_id;"  trong EvaluationCreateDto.
API Create mình không truyền id vào vì Entity tự sinh id

2022-03-31 03:31 UTC, NguyenVanHai1705 commented on pom.xml
> -        </dependency>
ok công

2022-03-31 03:31 UTC, NguyenVanHai1705 commented on src/main/java/motelRoom/entity/EvaluationEntity.java
> +    @Column(name = "time_rate")
ok  tây

2022-03-31 03:33 UTC, NguyenVanHai1705 commented on src/main/java/motelRoom/dto/valuation/EvaluationCreateDto.java
> +    private UUID evaluation_id;
ok tường

2022-03-31 07:44 UTC, thcong98 commented on src/main/java/motelRoom/controller/EvaluationController.java
> +
fomat lại khoảng cách và chuyển comment chú thích cho đoạn code này  nha bro!!!

2022-03-31 07:55 UTC, NguyenVanHai1705 commented
Ok công

Vào 14:45, T.5, 31 Th3, 2022 thcong98 ***@***.***> đã viết:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/main/java/motelRoom/controller/EvaluationController.java
> <https://github.com/theitm/my-room-mate/pull/5#discussion_r839282274>:
>
> > +    @GetMapping
>
> +    public List<EvaluationDetailDto> findAll(){
>
> +        return evaluationService.findAll();
>
> +    }
>
> +
>
> +   /**.........update evaluation....**/
>
> +
>
> +
>
> +
>
> +    /**......delete evaluation....**/
>
> +    @DeleteMapping("{id}")
>
> +    public ResponseEntity ***@***.*** UUID id){
>
> +        evaluationService.deleteById(id);
>
> +        return ResponseEntity.status(HttpStatus.ACCEPTED).build();
>
> +    }
>
> +
>
>
> fomat lại khoảng cách và chuyển comment chú thích cho đoạn code này nha
> bro!!!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/theitm/my-room-mate/pull/5#pullrequestreview-927137405>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATHQBP3ESME643W6Y7SO3PTVCVJXVANCNFSM5SBKLVJA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-01 03:52 UTC, kingonehit1 commented
Done

2022-04-01 03:53 UTC, merged